[server]
## style file for the OSD
style = "~/.config/swayosd/style.css"
top_margin = 0.92
max_volume = 100
show_percentage = true
## set format for the media player OSD
playerctl_format = "{artist} - {title}"
## Available values:
## artist, albumArtist, title, album, trackNumber, discNumber, autoRating
